In [1]:
%pylab inline --no-import-all

Populating the interactive namespace from numpy and matplotlib


In [34]:
def getWeights(g_1=1.,g_2=1.5):
    #Set the basis
    basis_g1 = np.array((0.,1.,1.,1.,1.))
    basis_g2 = np.array((1.,0.,1.,2.,3.))
    
    #define the formulae
    g1_t4 = lambda x,y: x*x*x*x + 0*y
    g1_t2_g2_t2  = lambda x,y: x*x*y*y
    g1_t3_g2 = lambda x,y: x*x*x*y
    g1_g2_t3 = lambda x,y: y*y*y*x
    g2_t4 = lambda x,y: y*y*y*y + 0*x

    a = np.zeros((5,5))

    for i in range(5):
        a[0,i] = g1_t4(basis_g1[i],basis_g2[i])
        a[2,i] = g1_t2_g2_t2(basis_g1[i],basis_g2[i])
        a[1,i] = g1_t3_g2(basis_g1[i],basis_g2[i])
        a[3,i] = g1_g2_t3(basis_g1[i],basis_g2[i])
        a[4,i] = g2_t4(basis_g1[i],basis_g2[i])

    print a
    
    b = np.linalg.inv(a)
    print b
    
    weight = np.zeros(5)
    #identify the weight

    for j in range(5):
        weight[j] = b[j,0]*g1_t4(g_1,g_2) + b[j,1]*g1_t3_g2(g_1,g_2) + b[j,2]*g1_t2_g2_t2(g_1,g_2) + b[j,3]*g1_g2_t3(g_1,g_2) + b[j,4]*g2_t4(g_1,g_2) 

    return weight


In [35]:
getWeights()

[[  0.   1.   1.   1.   1.]
 [  0.   0.   1.   2.   3.]
 [  0.   0.   1.   4.   9.]
 [  0.   0.   1.   8.  27.]
 [  1.   0.   1.  16.  81.]]
[[  0.          -6.          11.          -6.           1.        ]
 [  1.          -1.83333333   1.          -0.16666667   0.        ]
 [  0.           3.          -2.5          0.5          0.        ]
 [  0.          -1.5          2.          -0.5          0.        ]
 [  0.           0.33333333  -0.5          0.16666667   0.        ]]


array([ 0.5625, -0.0625,  0.5625,  0.5625, -0.0625])

array([[ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.]])